version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - run:
          name: Audit, lint, test, build and publish
          command: |
            yarn
            yarn lint
            yarn test
            yarn build
            npm set //registry.npmjs.org/:_authToken $NPM_API_TOKEN
            npm publish

workflows:
  export-workflow:
    jobs:
      - build
