name: Checks
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.3.1'
      - name: Install
        run: |
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
      - name: Build
        run: |
          yarn build
